---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint 
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        users: docker/login-action@v1
        with:
          username: ${{ secerets.DOCKERHUB_USER }}
          password: ${{ secerets.DOCKERHUB_TOKEN }}
      - name: Checkout
        users: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint 
        run: docker-compose run --rm app sh -c "flake8"